### ISSUE TITLE
[tracking] Checklist before release

### ISSUE THREAD

**Issue by uint** [CosmWasm/docs#72]
- [ ] do most articles/sections have tags?
- [ ] do examples showcase both `cw-storage-plus` and `cw-storey`? (using [tabs](http://localhost:3000/how-to-doc/tabs) like [here](https://github.com/CosmWasm/docs/pull/63/files#diff-219842e2dc8cbf4752caa4dbb88dabe5ef6410569e760a5cdf04e9ced13586e5))
- [ ] is naming consistent?
- [ ] is formatting more or less consistent? (nothing jarring)
- [ ] #78

**Comment by hashedone** [comment]
[ ] are we consistent with using code tags in section/article titles

**Comment by hashedone** [comment]
Added a point and converted into issue, to create a place for the discussion how to approach.
